# Generated by Django 4.2.9 on 2024-01-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_customuser_height_alter_customuser_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_name', models.CharField(max_length=255)),
                ('bmi_from', models.FloatField()),
                ('bmi_to', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_duration_minutes', models.PositiveIntegerField()),
                ('calories_burn', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_name', models.CharField(max_length=255)),
                ('preparation_time', models.CharField(max_length=50)),
                ('carbohydrate', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('energy', models.FloatField()),
                ('ingredients', models.TextField()),
                ('guide', models.TextField()),
                ('bmi_from', models.FloatField()),
                ('bmi_to', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='bmi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='daily_calories_burn_goal',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.activitytype')),
            ],
        ),
    ]
